"""add size_bytes to clip

Revision ID: 61bbe3a10ab1
Revises: 0f13c7563b5f
Create Date: 2026-02-12 09:23:49.777389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bbe3a10ab1'
down_revision: Union[str, Sequence[str], None] = '0f13c7563b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_bytes', sa.BigInteger(), nullable=True))
        batch_op.alter_column('metadata_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('pending', 'extracted', 'failed', 'partial', name='metadatastatusenum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.alter_column('metadata_status',
               existing_type=sa.Enum('pending', 'extracted', 'failed', 'partial', name='metadatastatusenum', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.drop_column('size_bytes')

    # ### end Alembic commands ###
