"""add card_identity to sd_card

Revision ID: a6b979e0914a
Revises: 20b1868c5313
Create Date: 2026-02-20 08:27:59.805245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b979e0914a'
down_revision: Union[str, Sequence[str], None] = '20b1868c5313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('clip_import', 'clip_probe', 'hash', 'thumb', 'contact_sheet', 'import_batch', 'probe_batch', 'import_file', 'probe_clip', 'sd_scan', 'thumb_batch', 'thumb_sd_batch', name='jobtypeenum', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('sd_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_identity', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_sd_card_card_identity'), ['card_identity'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sd_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sd_card_card_identity'))
        batch_op.drop_column('card_identity')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('clip_import', 'clip_probe', 'hash', 'thumb', 'contact_sheet', 'import_batch', 'probe_batch', 'import_file', 'probe_clip', 'sd_scan', 'thumb_batch', 'thumb_sd_batch', name='jobtypeenum', native_enum=False),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###
