"""initial schema

Revision ID: f3917b588506
Revises: d4a571c1951d
Create Date: 2026-01-07 14:36:24.852057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3917b588506'
down_revision: Union[str, Sequence[str], None] = 'd4a571c1951d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('repo_path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('camera', sa.Enum('front', 'rear', 'unknown', name='cameraenum', native_enum=False), nullable=False),
    sa.Column('mode', sa.Enum('continuous', 'event', 'manual', 'motion', 'parking', 'sos', 'unknown', name='modeenum', native_enum=False), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('codec', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('probe_version', sa.Integer(), nullable=True),
    sa.Column('probed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='metadatastatusenum', native_enum=False), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('metadata_error', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clip')),
    sa.UniqueConstraint('file_hash', name=op.f('uq_clip_file_hash'))
    )
    op.create_table('sd_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('volume_uid', sa.String(length=255), nullable=False),
    sa.Column('volume_label', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sd_card')),
    sa.UniqueConstraint('volume_uid', name=op.f('uq_sd_card_volume_uid'))
    )
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('thumb', 'contact_sheet', 'frame_extract', name='artifactkindenum', native_enum=False), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], name=op.f('fk_artifact_clip_id_clip')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact')),
    sa.UniqueConstraint('clip_id', 'kind', name='uq_artifact_clip_kind')
    )
    op.create_table('clip_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('sd_card_id', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], name=op.f('fk_clip_source_clip_id_clip')),
    sa.ForeignKeyConstraint(['sd_card_id'], ['sd_card.id'], name=op.f('fk_clip_source_sd_card_id_sd_card')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clip_source')),
    sa.UniqueConstraint('clip_id', name='uq_clip_source_clip_id'),
    sa.UniqueConstraint('sd_card_id', 'rel_path', name='uq_clip_source_sd_card_rel_path')
    )
    op.create_table('sd_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sd_card_id', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mtime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('import_state', sa.Enum('new', 'changed', 'imported', 'ignored', name='sdfileimportstateenum', native_enum=False), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sd_card_id'], ['sd_card.id'], name=op.f('fk_sd_file_sd_card_id_sd_card')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sd_file')),
    sa.UniqueConstraint('sd_card_id', 'rel_path', name='uq_sd_file_sd_card_rel_path')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('clip_import', 'clip_probe', 'hash', 'thumb', 'contact_sheet', name='jobtypeenum', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('queued', 'running', 'completed', 'failed', 'canceled', name='jobstateenum', native_enum=False), nullable=False),
    sa.Column('sd_file_id', sa.Integer(), nullable=True),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], name=op.f('fk_job_clip_id_clip'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sd_file_id'], ['sd_file.id'], name=op.f('fk_job_sd_file_id_sd_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('sd_file')
    op.drop_table('clip_source')
    op.drop_table('artifact')
    op.drop_table('sd_card')
    op.drop_table('clip')
    # ### end Alembic commands ###
